### ISSUE TITLE
API not responding

### ISSUE THREAD

**Issue by Crokepy** [EdixonAlberto/instagrapi#2]
I've spent 1 hour trying to get a user's followers and the API constantly throws an error

error:

ERROR-GET-PROFILE -> Cannot read property 'user' of undefined
(node:4924) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
    at Function.<anonymous> (C:\Users\Croque\Desktop\insta-node\node_modules\instagrapi\dist\InstagramApi.js:55:45)
    at step (C:\Users\Croque\Desktop\insta-node\node_modules\instagrapi\dist\InstagramApi.js:33:23)
    at Object.next (C:\Users\Croque\Desktop\insta-node\node_modules\instagrapi\dist\InstagramApi.js:14:53)
    at fulfilled (C:\Users\Croque\Desktop\insta-node\node_modules\instagrapi\dist\InstagramApi.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by EdixonAlberto** [comment]
Sorry for the delay, the library has had several changes that solve many of the problems and it is now working again in version 4.2.1, read the "readme" again please.

Specifically, this error is due to the fact that Instagram was blocking requests from the client side, now this was solved in two ways:

- The library now works with the "sessionId" of the users when they start a session on the page.
- The library is now only used on the server side to prevent other types of crashes.

You can see its correct operation in the examples that I show in the "readme".
